baseURL: "https://hrdn.ir/"
title: Hardening
pagination:
  pagerSize: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
defaultContentLanguage: fa
enableGitInfo: true

frontmatter:
  lastmod:
    - lastmod
    - :git
    - date
    - publishDate


#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  fa:
    languagedirection: rtl
    title: Ù‡Ø§Ø±Ø¯Ù†ÛŒÙ†Ú¯
    font: Shabnam
    weight: 10

  # en:
  #   languagedirection: ltr
  #   title: Hardening
  #   font: arial
  #   weight: 20

params:
  env: production  # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ù‡Ø§Ø±Ø¯Ù†ÛŒÙ†Ú¯ | ÙØ¹Ø§Ù„ Ø¯Ø± Ø­ÙˆØ²Ù‡ ØªØ­Ù‚ÛŒÙ‚Ø§Øª Ø§Ù…Ù†ÛŒØª Ø³Ø§ÛŒØ¨Ø±ÛŒ 
  description: Ø¨Ø§ Ø¨Ù‡Ø±Ù‡â€ŒÚ¯ÛŒØ±ÛŒ Ø§Ø² ØªØ­Ù‚ÛŒÙ‚Ø§Øª Ùˆ Ø±Ø§Ù‡Ú©Ø§Ø±Ù‡Ø§ÛŒ Ø§Ù…Ù†ÛŒØª Ø³Ø§ÛŒØ¨Ø±ÛŒØŒ Ø§Ù…Ù†ÛŒØª Ø³ÛŒØ³ØªÙ… Ù‡Ø§ÛŒ Ø¯ÛŒØ¬ÛŒØªØ§Ù„ Ø®ÙˆØ¯ Ø±Ø§ Ø¯Ø± Ø¨Ø±Ø§Ø¨Ø± ØªÙ‡Ø¯ÛŒØ¯Ø§Øª Ùˆ Ø­Ù…Ù„Ø§Øª Ø³Ø§ÛŒØ¨Ø±ÛŒ Ø§Ø±ØªÙ‚Ø§ Ø¯Ù‡ÛŒØ¯ 
  keywords: [Hardening, Portfolio Mansour Gashasbi, Mansour Gashasbi,Ù…Ù†ØµÙˆØ± Ú¯Ø´Ø³Ø¨ÛŒ ,Ù‡Ø§Ø±Ø¯Ù†ÛŒÙ†Ú¯,SAST, DAST, SCA, Static code Analysis, Dynamic code analysis, Code Security, Code Review,Code Metrics
  Code Quality, Ø§Ù…Ù†ÛŒØª Ø³ÙˆØ±Ø³ Ú©Ø¯, Ù…Ù‚Ø§ÙˆÙ… Ø³Ø§Ø²ÛŒ Ø´Ø¨Ú©Ù‡, Ø§Ù…Ù†ÛŒØª, Security of Source Code, Security, Code Secure, Bug Detection, Security Hardening, OS Hardening, Standard Hardening,
  harden of Systems, Vulnerability Management, Network Hardening, Ø§Ù…Ù†ÛŒØª Ø³Ø§ÛŒØ¨Ø±ÛŒ, Cyber Security]
  author: Mansour Gashasbi
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  defaultContentLanguage: fa
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true


  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/fav/favicon.ico"
    favicon16x16: "/fav/favicon-16x16.png"
    favicon32x32: "/fav/favicon-32x32.png"
    favicon64x64: "/fav/favicon-64x64.png"
    android-chrome-192x192: "/fav/android-chrome-192x192.png"
    android-chrome-512x512: "/fav/android-chrome-512x512.png"
    apple_touch_icon: "/fav/apple-touch-icon.png"
    #safari_pinned_tab: "/"

  label:



    text: "hrdn"
    # icon:
    # iconHeight: 35


  # home-info mode

  homeInfoParams:
    Title: "Ù‡Ø§Ø±Ø¯Ù†ÛŒÙ†Ú¯"
    Content:
      Ø¯Ø± Ø§ÛŒÙ† Ø§ÛŒÙ†Ø¬Ø§ØŒ Ø¨Ù‡ Ø¨Ø±Ø±Ø³ÛŒ Ø§Ø³ØªØ§Ù†Ø¯Ø§Ø±Ø¯Ù‡Ø§ Ùˆ Ø¨Ù‡ØªØ±ÛŒÙ† Ø±ÙˆØ´â€ŒÙ‡Ø§ Ø¨Ø±Ø§ÛŒ Ø¨Ù‡Ø¨ÙˆØ¯ Ø§Ù…Ù†ÛŒØªØŒ Ø¨Ù‡â€ŒÙˆÛŒÚ˜Ù‡ Ø§Ù…Ù†ÛŒØª Ø¯Ø± Ø­ÙˆØ²Ù‡ Ù†Ø±Ù…â€ŒØ§ÙØ²Ø§Ø± Ø®ÙˆØ§Ù‡Ù… Ù¾Ø±Ø¯Ø§Ø®Øª.
      

  searchInfoParams:
    Title: "Ù…ÙˆØ¶ÙˆØ¹ Ù…ÙˆØ±Ø¯ Ù†Ø¸Ø±ØªØ§Ù† Ø±Ø§ Ø¬Ø³ØªØ¬Ùˆ Ú©Ù†ÛŒØ¯..."
    Content:
      Ø¯Ø± Ù…ÙˆØ±Ø¯ Ø¬Ø³ØªØ¬Ùˆ

  social:
    - name: twitter
      url: "https://twitter.com/mgashasbi"


  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

    #  editPost:
    #  URL: "https://github.com/<path_to_repo>/content"
    #Text: "Suggest Changes" # edit text
    # appendFilePath: true # to append file path to Edit link

    #for search
    #https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]



menu:
  main:
    - identifier: categories
      name: Ø¯Ø³ØªÙ‡ Ø¨Ù†Ø¯ÛŒ
      url: /categories/
      weight: 40


    - identifier: tags
      name: Ø¨Ø±Ú†Ø³Ø¨ 
      url: /tags/
      weight: 30




    - identifier: posts
      name: Ù…Ù‚Ø§Ù„Ø§Øª 
      url: /posts/
      weight: 20


    - identifier: projects
    - name: Ù¾Ø±ÙˆÚ˜Ù‡ Ù‡Ø§
      pageRef: /projects/
      weight: 10
      url: /projects/

    - name: Ù¾Ø±ÙˆÚ˜Ù‡ Ø§ÙˆÙ„
      pageRef: /projects/111
      url: /projects/my-projects
      parent: Ù¾Ø±ÙˆÚ˜Ù‡ Ù‡Ø§
      weight: 1


    - identifier: aboutme
      name: Ø¯Ø±Ø¨Ø§Ø±Ù‡ Ù…Ù† 
      url: http://gashasbi.ir/
      weight: 50


    - identifier: search
      name: ğŸ”
      url: /search/
      weight: 60

# for a search page
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

# Default content language


